### ISSUE TITLE
Trying to understand

### ISSUE THREAD

**Issue by ugintl** [Bandyer/Bandyer-Android-CoreAV#1]
Just integrating it to my app will enable audio/video calling?

Will I be depending on any external service? for eg bandyer etc etc?

**Comment by kristiyanP** [comment]
This library enables simple audio/video communication. 
The communication is based on the creation&joining of the users in a room.

If you desire more advanced features such as signaling when one user calls the other, chat, whiteboard and others, you should consider our most advanced library which also includes UI fully customizable and presented by us [Bandyer Android SDK](https://github.com/Bandyer/Bandyer-Android-SDK).

Regarding the depending on any external service: 
Yes, you will depend on our system as there are a lot of complex server side logics handled by us.

If you desire more info about our pricing you may contact us at 
info@bandyer.com.
