### ISSUE TITLE
Room Token is not working becuse of jason parsing (expected _object but was string)

### ISSUE THREAD

**Issue by GoharAmin** [Bandyer/Bandyer-Android-CoreAV#2]

**Comment by kristiyanP** [comment]
This library requires a token that will be available only if you have a valid plan.

It enables simple audio/video communication.
The communication is based on the creation&joining of the users in a room.

If you desire more advanced features such as signaling when one user calls the other, chat, whiteboard and others, you should consider our most advanced library which also includes UI fully customizable and presented by us Bandyer Android SDK.

If you desire more info about our pricing you may contact us at
info@bandyer.com.
